"""add book metadata fields

Revision ID: 6ee4e72b9b64
Revises: 43ae60cea928
Create Date: 2026-02-17 23:16:05.676201

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6ee4e72b9b64'
down_revision: Union[str, Sequence[str], None] = '43ae60cea928'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('publisher', sa.String(length=200), nullable=True))
    op.add_column('books', sa.Column('published_date', sa.Date(), nullable=True))
    op.add_column('books', sa.Column('page_count', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('books', 'page_count')
    op.drop_column('books', 'published_date')
    op.drop_column('books', 'publisher')
    # ### end Alembic commands ###
