"""test

Revision ID: 46fda38378b7
Revises: 5f4cf6a80af3
Create Date: 2026-02-17 18:03:04.175884

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '46fda38378b7'
down_revision: Union[str, Sequence[str], None] = '5f4cf6a80af3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('edition', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('books', 'edition')
    # ### end Alembic commands ###
